name: Arti

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential libssl-dev pkg-config libssl-dev sudo curl wget git libsqlite3-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Get arti source
        run: git clone https://gitlab.torproject.org/tpo/core/arti.git

      - name: Build arti
        run: |
          cd arti
          cargo build -p arti --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: arti
          path: |
            arti
