name: sing-box Thin

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag to build (e.g., v1.13.0-rc.4). Leave empty to fetch the latest stable.'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    steps:
      - name: Get Target Tag
        id: get_tag
        run: |
          if [ "${{ github.event.inputs.tag_name }}" != "" ]; then
            SELECTED_TAG="${{ github.event.inputs.tag_name }}"
            echo "Using manually specified tag: $SELECTED_TAG"
          else
            SELECTED_TAG=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r .tag_name)
            echo "Latest Stable Tag: $SELECTED_TAG"
          fi
          echo "tag=$SELECTED_TAG" >> $GITHUB_OUTPUT

      - name: Checkout sing-box
        uses: actions/checkout@v6
        with:
          repository: SagerNet/sing-box
          ref: ${{ steps.get_tag.outputs.tag }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          
      - name: Build Binary
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
        run: |
          VERSION=${{ steps.get_tag.outputs.tag }}
          TAGS="with_quic with_acme"
          
          go build -v -tags "$TAGS" \
            -ldflags "-X github.com/sagernet/sing-box/constant.Version=$VERSION -s -w -buildid=" \
            -o sing-box-linux-amd64 \
            ./cmd/sing-box

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sing-box-${{ steps.get_tag.outputs.tag }}-linux-amd64
          path: sing-box-linux-amd64

      - name: Set TAG_NAME with UTC date
        run: echo "DATE=v$(date -u +'%Y.%m.%d-%H%M')" >> $GITHUB_ENV
          
      - name: Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          tag_name: "sing-box_thin-BUILD_${{ env.DATE }}"
          draft: false
          prerelease: false
          files: sing-box-linux-amd64
